### ISSUE TITLE
Possibly rename to something along the lines of "GameInfo"

### ISSUE THREAD

**Issue by f-rakete** [PrycilaCerqueira/P6_QuizMaker#1]
https://github.com/PrycilaCerqueira/P6_QuizMaker/blob/93ac4b775ca60fc601330b6a7907922f04964639/P6_QuizMaker/Game.cs#L9

because it really isn't a a game, but just some info about it :D

**Comment by PrycilaCerqueira** [comment]
I've rename the class from Game to GameInfo
