### ISSUE TITLE
bad naming

### ISSUE THREAD

**Issue by incredibleLeitman** [PrycilaCerqueira/P6_QuizMaker#10]
https://github.com/PrycilaCerqueira/P6_QuizMaker/blob/bd4ce134a0c22c6d0956a54b60bc9f77b39462cc/P6_QuizMaker/Program.cs#L13

just "confirmation" is pretty generic, I would suggest some more fitting variable name such as "continuePlaying" or something like that

**Comment by PrycilaCerqueira** [comment]
Var has been renamed.
