### ISSUE TITLE
"continue" after preparing questions seems a bit missplaced

### ISSUE THREAD

**Issue by incredibleLeitman** [PrycilaCerqueira/P6_QuizMaker#13]
![image](https://user-images.githubusercontent.com/24638443/199488928-e86d7b11-952d-41b4-8643-5508bebea144.png)

As a user I suggest that this prompt asks me, if I want to add more questions instead of starting to play.

I am not sure if this prompt even make sense at this place, 
maybe a better flow would be to first ask the users if they want to edit the quiz card db (or create if it doesn't exist)
or just play the game (if a quizDB could be loaded)

related to #11

**Comment by PrycilaCerqueira** [comment]
I just removed the prompt to continue the game.
