### ISSUE TITLE
in-game ID, name and ID number

### ISSUE THREAD

**Issue by incredibleLeitman** [PrycilaCerqueira/P6_QuizMaker#14]
![image](https://user-images.githubusercontent.com/24638443/199490019-d6fa8014-eac9-453c-a026-a8bd7e8a7c98.png)

![image](https://user-images.githubusercontent.com/24638443/199490352-59aad89c-525a-4175-88fe-f30259870613.png)
I got confused when asked to enter a in-game ID and after that for an ID number, which are obvsly not the same?

Is there a reason why you are using internal in-game IDs AND names, both provided by the user?

A thing you could do is that you automatically choose the first player and then one after another instead of letting the users decide?

**Comment by PrycilaCerqueira** [comment]
The in-game ID is not a number. It works as a nickname for players.

**Comment by incredibleLeitman** [comment]
> The in-game ID is not a number. It works as a nickname for players.
Yeah I understood this part, but not why you are requesting a user "in-game ID" (which also could be renamed to "username" or "nickname" to be less confusing because ID usually means a unique series of digits) AND requesting the full name? Do you ever use the full name again anywhere in your program?

> I didn't create a flow for player auto-selection because of my personal experience, where I had to wait for the current player to finish their turn. The downside is that if the player, for some reason, has to leave the room, the other players have to restart the game to have an accurate score instead of just skipping the missing person.

Oh I get that, great thinking there 👍

**Comment by PrycilaCerqueira** [comment]
I've removed the field nickname as well as changed from full name to name.
