### ISSUE TITLE
Initialize Random only once

### ISSUE THREAD

**Issue by incredibleLeitman** [PrycilaCerqueira/P6_QuizMaker#16]
You don't need to create a new random object for every step in your while loop (which is also nested within a do)
https://github.com/PrycilaCerqueira/P6_QuizMaker/blob/bd4ce134a0c22c6d0956a54b60bc9f77b39462cc/P6_QuizMaker/Program.cs#L50

Instead you want to create it once on top of your main (or even better as static variable) and only access it multiple times

**Comment by PrycilaCerqueira** [comment]
Adjusted the code.
 https://github.com/PrycilaCerqueira/P6_QuizMaker/blob/ed2cab2251d2bd904838b5dc467446e6dcf0103c/P6_QuizMaker/Program.cs#L14
