### ISSUE TITLE
Could be one method with a gameinfo parameter

### ISSUE THREAD

**Issue by f-rakete** [PrycilaCerqueira/P6_QuizMaker#2]
https://github.com/PrycilaCerqueira/P6_QuizMaker/blob/93ac4b775ca60fc601330b6a7907922f04964639/P6_QuizMaker/Program.cs#L13-L14

**Comment by PrycilaCerqueira** [comment]
I am using them separately because I won't use the UI.PrintGameInstructions(trivia.Description);, but I will use the UI.PrintGameHeadline(trivia.Title); multiple times.
