### ISSUE TITLE
Loads of UI code here - refactor?

### ISSUE THREAD

**Issue by f-rakete** [PrycilaCerqueira/P6_QuizMaker#3]
https://github.com/PrycilaCerqueira/P6_QuizMaker/blob/93ac4b775ca60fc601330b6a7907922f04964639/P6_QuizMaker/Program.cs#L18-L39

**Comment by f-rakete** [comment]
same goes for this, that could be one UI method Quiz GetQuizCard() like in #4

**Comment by PrycilaCerqueira** [comment]
The block was re-done
https://github.com/PrycilaCerqueira/P6_QuizMaker/blob/1fc055bff0692cbc033aa057e4e6fdf991a0dd78/P6_QuizMaker/Program.cs#L16-L17
