### ISSUE TITLE
Refactor to UI method?

### ISSUE THREAD

**Issue by f-rakete** [PrycilaCerqueira/P6_QuizMaker#4]
https://github.com/PrycilaCerqueira/P6_QuizMaker/blob/93ac4b775ca60fc601330b6a7907922f04964639/P6_QuizMaker/Program.cs#L51-L60

**Comment by PrycilaCerqueira** [comment]
I will use it for recording the players' scores.

**Comment by f-rakete** [comment]
this part of the code could be one UI method like List<Player> GetNewPlayers();

**Comment by PrycilaCerqueira** [comment]
The block was updated
https://github.com/PrycilaCerqueira/P6_QuizMaker/blob/1fc055bff0692cbc033aa057e4e6fdf991a0dd78/P6_QuizMaker/Program.cs#L27-L29
