### ISSUE TITLE
First Answer check in Loop

### ISSUE THREAD

**Issue by f-rakete** [PrycilaCerqueira/P6_QuizMaker#5]
https://github.com/PrycilaCerqueira/P6_QuizMaker/blob/93ac4b775ca60fc601330b6a7907922f04964639/P6_QuizMaker/Program.cs#L27-L35

Do you really need this check  `if (numOfAnswers != 0)` ?

if you only want to do an action once in the beginning, why not move it outside (on top) of the loop 🙈

**Comment by PrycilaCerqueira** [comment]
Thank you for the tip. I missed it =)
The code was adjusted.
