### ISSUE TITLE
Handling used Questions

### ISSUE THREAD

**Issue by f-rakete** [PrycilaCerqueira/P6_QuizMaker#6]
https://github.com/PrycilaCerqueira/P6_QuizMaker/blob/93ac4b775ca60fc601330b6a7907922f04964639/P6_QuizMaker/Program.cs#L82-L89

Currently you're marking used questions with an # 
this could lead to errors if somebody actually uses this symbol in a question when entering it.
also IMO it's a bit clunky :D 

how about you remove the question from your list after you used it?

**Comment by PrycilaCerqueira** [comment]
Thank you! I didn't think about it hahaha...
I updated the code:

https://github.com/PrycilaCerqueira/P6_QuizMaker/blob/e7ef70460f56cefde3751f6ae5ed3e7231b21c29/P6_QuizMaker/Program.cs#L90-L98
