### ISSUE TITLE
why is this not simply a for loop 🙃

### ISSUE THREAD

**Issue by f-rakete** [PrycilaCerqueira/P6_QuizMaker#7]
https://github.com/PrycilaCerqueira/P6_QuizMaker/blob/93ac4b775ca60fc601330b6a7907922f04964639/P6_QuizMaker/UI.cs#L161-L162

**Comment by f-rakete** [comment]
also maybe think about randomizing the answers, otherwise the first answer will always be the correct one :D

**Comment by PrycilaCerqueira** [comment]
I didn't use the **for** loop because with the **for each** I can easily access the string element in the list to modify before presenting it to the players. 
The answers are randomized on Program.cs line 81 and 82.

**Comment by PrycilaCerqueira** [comment]
All the Right Answer is marked with the *.
Before displaying the answers for players to select from them, I need to remove the * quickly. The ForEach provides me with an easy way to do it.
