### ISSUE TITLE
Is a swtich statement necessary? 

### ISSUE THREAD

**Issue by f-rakete** [PrycilaCerqueira/P6_QuizMaker#8]
https://github.com/PrycilaCerqueira/P6_QuizMaker/blob/93ac4b775ca60fc601330b6a7907922f04964639/P6_QuizMaker/UI.cs#L198-L215

hint 
![image](https://user-images.githubusercontent.com/69428398/195543935-bcfa8479-77cf-4efc-a73b-6d72da8e32c6.png)

**Comment by PrycilaCerqueira** [comment]
Removed the switch as it is no longer necessary.

**Comment by PrycilaCerqueira** [comment]
Removed the switch as it is no longer necessary.

**Comment by PrycilaCerqueira** [comment]
Yes, it is necessary because it references my Answer list elements for the multiple-choice options (1 to 5) as the user is required to enter a number.
