### ISSUE TITLE
remove unused usings

### ISSUE THREAD

**Issue by incredibleLeitman** [PrycilaCerqueira/P6_QuizMaker#9]
https://github.com/PrycilaCerqueira/P6_QuizMaker/blob/bd4ce134a0c22c6d0956a54b60bc9f77b39462cc/P6_QuizMaker/Program.cs#L1-L3

You can right click on the using-part and select "Remove and Sort usings" or use the default shortcut "Ctrl+R, Ctrl + G"
Make sure you keep your usings straight in all your files

**Comment by PrycilaCerqueira** [comment]
Done!
